program: sweep_train_jtb.py
method: random
metric:
  goal: maximize
  name: test_accuracy_postp
parameters:
  embeddings:
    values:
      - "[16]"
      - "[32]"
      - "[64]"
      - "[96]"
      - "[128]"
      - "[256]"
    distribution: categorical
  weight_decay:
    values:
      - 0.0005 
      - 0.005
      - 0.05
    distribution: categorical
  encoder_type:
    values:
      - transformer
    distribution: categorical
  activation:
    values:
      - gelu
    distribution: categorical
  n_layers:
    max: 4
    min: 1
    distribution: int_uniform
  n_hidden:
    values:
      - 256
      - 128
      - 64
      - 32
    distribution: categorical
  biaffine:
    values:
      - True
      - False
    distribution: categorical
  n_heads:
    values:
      - 8
      - 4
      - 2
      - 1
    distribution: categorical
  dropout:
    max: 0.5
    min: 0
    distribution: uniform
  lr:
    max: 0.0005
    min: 0.00009
    distribution: uniform
  loss_type:
    values:
      - "both"
    distribution: categorical
  use_pos_weight:
    values:
      - False
    distribution: categorical
  optimizer:
    values:
      - warmadamw
    distribution: categorical
  warmup_steps:
    values:
      - 50
    distribution: categorical
