program: sweep_train_jtb.py
method: bayes
metric:
  goal: maximize
  name: test_ctree_sim
parameters:
  embeddings:
    values:
      - "[16]"
      - "[32]"
      - "[64]"
      - "[96]"
      - "[128]"
      - "[256]"
    distribution: categorical
  weight_decay:
    values:
      - 0.0005 
      - 0.005
      - 0.05
    distribution: categorical
  encoder_type:
    values:
      - rnn
      - transformer
    distribution: categorical
  activation:
    values:
      - relu
      - gelu
    distribution: categorical
  n_layers:
    max: 4
    min: 1
    distribution: int_uniform
  n_hidden:
    values:
      - 256
      - 128
      - 64
      - 32
    distribution: categorical
  biaffine:
    values:
      - True
      - False
    distribution: categorical
  n_heads:
    values:
      - 8
      - 4
      - 2
      - 1
    distribution: categorical
  dropout:
    max: 0.5
    min: 0
    distribution: uniform
  lr:
    values:
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
      - 0.00005
      - 0.00001
    distribution: categorical
  loss_type:
    values:
      - "ce"
      - "bce"
      - "both"
    distribution: categorical
  use_pos_weight:
    values:
      - False
    distribution: categorical
  optimizer:
    values:
      - warmadamw
      - warmadam
    distribution: categorical
  warmup_steps:
    values:
      - 1000
      - 800
      - 600
      - 400
      - 200
      - 100
      - 50
    distribution: categorical
